"""議事系統服務層

結構：
  _session.py  - 會議 CRUD / 生命週期
  _agenda.py   - 議程 / 出勤 / 法案推進 / 議事事件
  _voting.py   - 表決 / 計時 / 動議 / 決議 / 迴避 / 發言隊列
  _payloads.py - 螢幕 / 加入 / 工作台 / 會議紀錄 payload
"""

from api.services.meeting._agenda import (
    active_voting_class_for_user,
    advance_agenda_regulation,
    check_in,
    create_agenda_item,
    create_agenda_item_for_council_proposal,
    create_agenda_item_for_regulation,
    create_artifact_link,
    delete_agenda_item,
    delete_artifact_link,
    import_attendance_source,
    list_events,
    list_proposable_regulations,
    record_event,
    reorder_agenda_items,
    resolve_attendance_source,
    seed_voter_roster,
    sync_proposals_to_agenda,
    update_agenda_item,
    update_artifact_link,
    update_attendance,
    upsert_attendance,
)
from api.services.meeting._payloads import (
    decorate_vote,
    join_payload,
    minutes_payload,
    screen_payload,
    vote_roster_payload,
    workspace_payload,
)
from api.services.meeting._session import (
    confirm_meeting,
    create_meeting,
    get_meeting,
    get_meeting_by_join_token,
    get_meeting_by_screen_token,
    list_meetings,
    transition_meeting,
    update_meeting,
)
from api.services.meeting._voting import (
    _format_resolution,
    _vote_tally,
    add_recusal,
    attendance_summary,
    cast_ballot,
    close_vote,
    create_decision,
    create_motion,
    create_request,
    create_speech_queue_item,
    create_vote,
    current_timer_remaining,
    eligible_voter_count,
    extend_speech,
    finish_speech,
    get_or_create_screen_state,
    get_or_create_timer_state,
    open_vote,
    pause_speech,
    record_acclamation,
    record_manual_tally,
    recorder_cast_ballot,
    recused_voter_count,
    remove_recusal,
    reorder_speech_queue,
    resume_speech,
    start_speech,
    update_decision,
    update_motion,
    update_request_status,
    update_screen_state,
    update_speech_queue_item,
    update_vote,
)

__all__ = [
    # session
    "get_meeting",
    "get_meeting_by_screen_token",
    "get_meeting_by_join_token",
    "list_meetings",
    "create_meeting",
    "update_meeting",
    "transition_meeting",
    "confirm_meeting",
    # agenda
    "list_proposable_regulations",
    "sync_proposals_to_agenda",
    "advance_agenda_regulation",
    "delete_agenda_item",
    "seed_voter_roster",
    "active_voting_class_for_user",
    "record_event",
    "list_events",
    "create_agenda_item",
    "reorder_agenda_items",
    "create_artifact_link",
    "update_artifact_link",
    "delete_artifact_link",
    "create_agenda_item_for_regulation",
    "create_agenda_item_for_council_proposal",
    "update_agenda_item",
    "resolve_attendance_source",
    "import_attendance_source",
    "check_in",
    "upsert_attendance",
    "update_attendance",
    # voting
    "create_vote",
    "create_motion",
    "update_motion",
    "create_decision",
    "update_decision",
    "get_or_create_screen_state",
    "get_or_create_timer_state",
    "update_screen_state",
    "update_vote",
    "current_timer_remaining",
    "create_speech_queue_item",
    "update_speech_queue_item",
    "reorder_speech_queue",
    "start_speech",
    "pause_speech",
    "resume_speech",
    "finish_speech",
    "extend_speech",
    "open_vote",
    "close_vote",
    "cast_ballot",
    "recorder_cast_ballot",
    "record_manual_tally",
    "record_acclamation",
    "add_recusal",
    "remove_recusal",
    "create_request",
    "update_request_status",
    "eligible_voter_count",
    "recused_voter_count",
    "attendance_summary",
    # payloads
    "decorate_vote",
    "vote_roster_payload",
    "screen_payload",
    "join_payload",
    "workspace_payload",
    "minutes_payload",
]
