"""公文服務層 - CRUD、狀態機（含退回至上一關）、字號生成、組織可見性

結構：
  _serial.py    - 字號自動生成 + 字號模板 CRUD
  _template.py  - 公文內容範本 CRUD + 從範本建立草稿
  _access.py    - 可見性 / 存取控制 / 查詢輔助
  _lifecycle.py - 公文 CRUD / 狀態機 / 審核 / 代行授權 / 受文者
"""

from api.services.document._access import (
    REDACTED_CONFIDENTIAL_TEXT,
    SENSITIVE_DOCUMENT_CLASSIFICATIONS,
    _active_assignment_exists_for_viewer,
    _apply_assignment_delegate_to_approval,
    _build_visibility_filter,
    _delegation_query_with_relations,
    _doc_query_for_list,
    _doc_query_with_relations,
    _has_active_org_membership,
    _resolve_active_delegate_assignment,
    _sync_pending_approval_delegations,
    build_document_list_items,
    can_anonymous_access_document,
    check_document_access,
    get_approval_delegation,
    get_document,
    get_document_by_serial,
    is_sensitive_document,
    list_documents,
    user_has_full_document_access,
)
from api.services.document._lifecycle import (
    PRIMARY_RECIPIENT_TYPES,
    _get_current_approval,
    _lock_document,
    approve_step,
    archive_document,
    create_approval_delegation,
    create_document,
    deactivate_approval_delegation,
    delete_document,
    get_recipient_for_admin,
    is_primary_variant,
    issue_document_directly,
    list_approval_delegations,
    recall_document,
    reject_step,
    reject_to_previous_step,
    resolve_recipient_match,
    set_delegate,
    submit_document,
    suggest_approvers,
    update_approval_delegation,
    update_document,
    upsert_recipients,
)
from api.services.document._serial import (
    build_org_serial_prefix,
    create_serial_template,
    deactivate_serial_template,
    generate_serial_from_template,
    get_serial_template,
    list_serial_templates,
    update_serial_template,
)
from api.services.document._template import (
    _recipients_from_json,
    _recipients_to_json,
    _validate_document_template,
    create_document_from_template,
    create_document_template,
    deactivate_document_template,
    get_document_template,
    list_document_templates,
    update_document_template,
)

__all__ = [
    # serial
    "generate_serial_from_template",
    "build_org_serial_prefix",
    "create_serial_template",
    "get_serial_template",
    "list_serial_templates",
    "deactivate_serial_template",
    "update_serial_template",
    # template
    "_recipients_to_json",
    "_recipients_from_json",
    "_validate_document_template",
    "create_document_template",
    "get_document_template",
    "list_document_templates",
    "update_document_template",
    "deactivate_document_template",
    "create_document_from_template",
    # access
    "REDACTED_CONFIDENTIAL_TEXT",
    "SENSITIVE_DOCUMENT_CLASSIFICATIONS",
    "_active_assignment_exists_for_viewer",
    "_doc_query_for_list",
    "_doc_query_with_relations",
    "_delegation_query_with_relations",
    "_has_active_org_membership",
    "_resolve_active_delegate_assignment",
    "_apply_assignment_delegate_to_approval",
    "_sync_pending_approval_delegations",
    "get_document",
    "get_document_by_serial",
    "is_sensitive_document",
    "can_anonymous_access_document",
    "user_has_full_document_access",
    "check_document_access",
    "_build_visibility_filter",
    "build_document_list_items",
    "list_documents",
    # lifecycle
    "create_document",
    "update_document",
    "submit_document",
    "issue_document_directly",
    "suggest_approvers",
    "_lock_document",
    "approve_step",
    "reject_step",
    "reject_to_previous_step",
    "upsert_recipients",
    "recall_document",
    "archive_document",
    "delete_document",
    "list_approval_delegations",
    "get_approval_delegation",
    "create_approval_delegation",
    "update_approval_delegation",
    "deactivate_approval_delegation",
    "set_delegate",
    "_get_current_approval",
    "PRIMARY_RECIPIENT_TYPES",
    "resolve_recipient_match",
    "is_primary_variant",
    "get_recipient_for_admin",
]
