"""校商訂購系統服務層

結構：
  _catalog.py - 分類 / 系列 / 商品 CRUD / 變體 / 瀏覽樹
  _orders.py  - 購物車 / 訂單 CRUD / 序列化 / 統計
  _export.py  - 報表匯出
"""

from api.services.shop._catalog import (
    activate_product,
    add_variant_group,
    add_variant_option,
    build_catalog_tree,
    create_category,
    create_product,
    create_series,
    deactivate_product,
    delete_category,
    delete_series,
    delete_variant_group,
    delete_variant_option,
    generate_order_serial,
    get_category,
    get_product,
    get_series,
    get_variant_group,
    get_variant_option,
    list_categories,
    list_products,
    list_series,
    update_category,
    update_product,
    update_series,
    update_variant_group,
    update_variant_option,
)
from api.services.shop._export import (
    export_orders_csv,
    export_orders_excel,
)
from api.services.shop._orders import (
    _assert_activity_open,
    _cart_item_availability,
    _create_order_from_items,
    _options_delta,
    _options_signature,
    _order_activity_id,
    _order_items_to_cart_items,
    _resolve_selected_options,
    add_cart_item,
    cancel_order,
    checkout,
    clear_cart,
    create_direct_order,
    get_order,
    get_or_create_cart,
    list_orders,
    order_summary,
    remove_cart_item,
    replace_order_items,
    serialize_cart,
    serialize_order,
    serialize_order_item,
    serialize_order_list_item,
    set_order_paid,
    update_cart_item,
)

__all__ = [
    # catalog
    "generate_order_serial",
    "get_category",
    "list_categories",
    "create_category",
    "update_category",
    "delete_category",
    "get_series",
    "list_series",
    "create_series",
    "update_series",
    "delete_series",
    "get_product",
    "list_products",
    "create_product",
    "update_product",
    "activate_product",
    "deactivate_product",
    "get_variant_group",
    "add_variant_group",
    "update_variant_group",
    "delete_variant_group",
    "get_variant_option",
    "add_variant_option",
    "update_variant_option",
    "delete_variant_option",
    "build_catalog_tree",
    # orders
    "_resolve_selected_options",
    "_options_signature",
    "_options_delta",
    "get_or_create_cart",
    "add_cart_item",
    "update_cart_item",
    "remove_cart_item",
    "clear_cart",
    "_cart_item_availability",
    "serialize_cart",
    "_assert_activity_open",
    "_order_activity_id",
    "_create_order_from_items",
    "_order_items_to_cart_items",
    "create_direct_order",
    "checkout",
    "get_order",
    "list_orders",
    "serialize_order_item",
    "serialize_order",
    "serialize_order_list_item",
    "cancel_order",
    "replace_order_items",
    "set_order_paid",
    "order_summary",
    # export
    "export_orders_excel",
    "export_orders_csv",
]
