#!/usr/bin/env node
/**
 * scripts/generate-bridge.mjs
 *
 * 1. 讀取 apps/web/src/lib/api-types.ts，擷取 components.schemas 下的所有 schema 名稱
 * 2. 生成 apps/web/src/lib/api-bridge.ts
 *    - 每個 schema → `export type X = components['schemas']['X']`
 *    - 這樣其他檔案可以 `import type { DocumentOut } from '@/lib/api-bridge'`
 *      而不用直接用 `components['schemas']['DocumentOut']` 這種冗長語法
 * 3. 讀取 apps/web/src/lib/types.ts，擷取所有已匯出名稱
 * 4. 輸出統計：哪些名稱已由 api-bridge 覆蓋、哪些仍需手寫
 *
 * 執行：
 *   node scripts/generate-bridge.mjs
 * 或加進 npm script：
 *   "generate:bridge": "node ../../scripts/generate-bridge.mjs"
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, "..");
const API_TYPES = resolve(REPO, "apps/web/src/lib/api-types.ts");
const HAND_TYPES = resolve(REPO, "apps/web/src/lib/types.ts");
const OUT = resolve(REPO, "apps/web/src/lib/api-bridge.ts");

// ── 1. 從 api-types.ts 擷取 components.schemas 下的 schema 名稱 ───────────────

const apiTypesContent = readFileSync(API_TYPES, "utf8");

// schemas block 在 `components { schemas: { ... } }` 內
// schema 名稱：大寫開頭一般名稱，或 api__schemas__* 命名空間名稱（含雙底線前綴）
const schemaNameRe = /^ {8}((?:[a-z]+__)+[A-Za-z]\w*|[A-Z][A-Za-z0-9]*):/gm;
const schemaNames = new Set();
let m;
while ((m = schemaNameRe.exec(apiTypesContent)) !== null) {
  schemaNames.add(m[1]);
}
console.error(`[generate-bridge] api-types.ts 中找到 ${schemaNames.size} 個 schema`);

// ── 2. 生成 api-bridge.ts ─────────────────────────────────────────────────────

const sorted = [...schemaNames].sort();
const lines = [
  "/**",
  " * api-bridge.ts — AUTO-GENERATED, DO NOT EDIT",
  " *",
  " * Generated by scripts/generate-bridge.mjs",
  " * Re-exports all schemas from api-types.ts as named types for convenient import.",
  " *",
  " * Regenerate with:  node scripts/generate-bridge.mjs",
  " * Or after updating openapi.json: npm run generate:types && node ../../scripts/generate-bridge.mjs",
  " */",
  "",
  "import type { components } from './api-types'",
  "",
  "// prettier-ignore-start",
  ...sorted.map((name) => `export type ${name} = components['schemas']['${name}']`),
  "// prettier-ignore-end",
  "",
];
writeFileSync(OUT, lines.join("\n"), "utf8");
console.error(`[generate-bridge] 寫入 ${OUT}（${sorted.length} 個 type alias）`);

// ── 3. 分析 types.ts — 哪些名稱已被 api-bridge 覆蓋 ─────────────────────────

const handTypesContent = readFileSync(HAND_TYPES, "utf8");
const handExportRe = /^export (?:type|interface|const|enum) ([A-Z][A-Za-z0-9]*)/gm;
const handNames = new Set();
while ((m = handExportRe.exec(handTypesContent)) !== null) {
  handNames.add(m[1]);
}

const covered = [...handNames].filter((n) => schemaNames.has(n)).sort();
const missing = [...handNames].filter((n) => !schemaNames.has(n)).sort();

console.error(`\n[generate-bridge] types.ts 匯出分析：`);
console.error(`  總計：        ${handNames.size} 個`);
console.error(`  已有 schema：  ${covered.length} 個（可切換成 api-bridge 匯入）`);
console.error(`  仍需手寫：     ${missing.length} 個`);

if (missing.length > 0) {
  console.error(`\n[generate-bridge] 仍需手寫的名稱（未在 api-types.ts 中的 schema）：`);
  missing.forEach((n) => console.error(`  - ${n}`));
}

// ── 4. 為 types.ts 中名稱與 schema 不同的型別額外生成別名 ─────────────────────
// 格式：{ "types.ts 中的名稱": "api-types.ts schema 名稱" }
const ALIAS_MAP = {
  // Activity 模組（types.ts 省略 Out 後綴）
  Activity: "ActivityOut",
  ActivityConvener: "ActivityConvenerOut",
  ActivityMember: "ActivityMemberOut",
  ActivityRole: "ActivityRoleOut",
  DiscordActivityWorkspace: "DiscordActivityWorkspaceOut",
  // Governance 決策（命名空間衝突，api-types 加 module 前綴）
  DecisionCreate: "api__schemas__governance__DecisionCreate",
  DecisionOut: "api__schemas__governance__DecisionOut",
  DecisionUpdate: "api__schemas__governance__DecisionUpdate",
  // Matter
  MatterLinkRef: "MatterLinkRefOut",
  MatterSpawnResult: "MatterSpawnOut",
  // Meeting 子型別（types.ts 加 Meeting 前綴）
  MeetingAgendaAttachmentOut: "AgendaAttachmentOut",
  MeetingAgendaItemOut: "AgendaItemOut",
  MeetingArtifactLinkOut: "ArtifactLinkOut",
  MeetingArtifactType: "ArtifactLinkType",
  MeetingAttendanceOut: "AttendanceOut",
  MeetingAttendanceSourceOut: "AttendanceSourceOut",
  MeetingAttendanceSourcePreviewOut: "AttendanceSourcePreviewOut",
  MeetingBallotOut: "BallotOut",
  MeetingClassBrief: "SchoolClassBrief",
  MeetingDecisionOut: "api__schemas__meeting__DecisionOut",
  MeetingMotionOut: "MotionOut",
  MeetingRecusalOut: "RecusalOut",
  MeetingRegulationBrief: "RegulationBrief",
  MeetingScreenReadingMode: "ScreenReadingMode",
  MeetingScreenStateOut: "ScreenStateOut",
  MeetingSpeechQueueItemOut: "SpeechQueueItemOut",
  MeetingSpeechQueueStatus: "SpeechQueueStatus",
  MeetingTimerStateOut: "TimerStateOut",
  MeetingTimerStatus: "TimerStatus",
  MeetingUserBrief: "UserBrief",
  MeetingVoteOption: "VoteOption",
  MeetingVoteOut: "VoteOut",
  MeetingVoteRecordMethod: "VoteRecordMethod",
  MeetingVoteRosterClassOut: "VoteRosterClassOut",
  MeetingVoteRosterOut: "VoteRosterOut",
  MeetingVoteTallyOut: "VoteTallyOut",
  // Public declarations
  AmendmentComparisonRow: "AmendmentComparisonRowOut",
  // Notification
  NotificationPreferences: "NotificationPreferencesOut",
  // Defense
  DefenseRule: "DefenseRuleOut",
  // Seating
  SeatBookingOut: "api__schemas__seating__AssignmentOut",
};

// 驗證別名目標確實存在於 schema 清單中
const missingAliasTargets = Object.entries(ALIAS_MAP).filter(
  ([, target]) => !schemaNames.has(target),
);
if (missingAliasTargets.length > 0) {
  console.error(
    `[generate-bridge] ⚠ 以下別名目標不存在於 api-types.ts 的 schemas：`,
  );
  missingAliasTargets.forEach(([alias, target]) =>
    console.error(`  ${alias} → ${target} (NOT FOUND)`),
  );
}

// 把別名加入 api-bridge.ts
const aliasLines = Object.entries(ALIAS_MAP)
  .filter(([, target]) => schemaNames.has(target))
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([alias, target]) => `export type ${alias} = components['schemas']['${target}']`);

if (aliasLines.length > 0) {
  const bridgeContent = readFileSync(OUT, "utf8");
  const updatedContent = bridgeContent.replace(
    "// prettier-ignore-end",
    `// prettier-ignore-end\n\n// ── 別名（types.ts 使用不同名稱）────────────────────────────────────────────\n// prettier-ignore-start\n${aliasLines.join("\n")}\n// prettier-ignore-end`,
  );
  writeFileSync(OUT, updatedContent, "utf8");
  console.error(`[generate-bridge] 加入 ${aliasLines.length} 個別名 alias`);
}

// 更新 covered/missing 統計（含別名）
const allBridgeNames = new Set([...schemaNames, ...Object.keys(ALIAS_MAP).filter((k) => schemaNames.has(ALIAS_MAP[k]))]);
const coveredFinal = [...handNames].filter((n) => allBridgeNames.has(n)).sort();
const missingFinal = [...handNames].filter((n) => !allBridgeNames.has(n)).sort();

console.error(`\n[generate-bridge] 最終覆蓋率（含別名）：`);
console.error(`  總計：        ${handNames.size} 個`);
console.error(`  已覆蓋：      ${coveredFinal.length} 個`);
console.error(`  仍需手寫：    ${missingFinal.length} 個`);
if (missingFinal.length > 0) {
  console.error(`\n[generate-bridge] 仍需手寫的型別（建議保留在 types.ts）：`);
  missingFinal.forEach((n) => console.error(`  - ${n}`));
}

console.log(JSON.stringify({ covered: coveredFinal, missing: missingFinal, total: handNames.size }, null, 2));
