"""drop unused meetings notice email message id index

Revision ID: 0875b2aea8fe
Revises: 65d22994f220
Create Date: 2026-07-06 01:23:35.334179

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0875b2aea8fe"
down_revision: str | Sequence[str] | None = "65d22994f220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meetings_notice_email_message_id"), table_name="meetings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_meetings_notice_email_message_id"),
        "meetings",
        ["notice_email_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###
