"""整合投稿公告設定

Revision ID: 10f28626ce9c
Revises: ffff8afe1b1d
Create Date: 2026-07-20 02:55:43.705680

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10f28626ce9c"
down_revision: str | Sequence[str] | None = "ffff8afe1b1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchandise_submission_settings",
        sa.Column("announcement_title", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "merchandise_submission_settings",
        sa.Column("show_announcement_popup", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "merchandise_submission_settings", sa.Column("announcement_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "merchandise_submission_settings",
        "announcements",
        ["announcement_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "merchandise_submission_settings", type_="foreignkey")
    op.drop_column("merchandise_submission_settings", "announcement_id")
    op.drop_column("merchandise_submission_settings", "show_announcement_popup")
    op.drop_column("merchandise_submission_settings", "announcement_title")
    # ### end Alembic commands ###
