"""字號模板上級前綴設定

Revision ID: 1602a7684c1d
Revises: 20260906110000
Create Date: 2026-09-09 15:14:14.453747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1602a7684c1d"
down_revision: str | Sequence[str] | None = "20260906110000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_serial_templates",
        sa.Column("inherit_parent_prefix", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_serial_templates", "inherit_parent_prefix")
    # ### end Alembic commands ###
