"""drop_serial_seq_column

Revision ID: 360cbbf2ae06
Revises: f73343a3659d
Create Date: 2026-04-09 22:47:30.027729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360cbbf2ae06'
down_revision: Union[str, Sequence[str], None] = 'f73343a3659d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'serial_seq')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('serial_seq', sa.BIGINT(), server_default=sa.text("nextval('document_serial_seq'::regclass)"), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
