"""add_weight_to_position_and_meeting_notice_fields

Revision ID: 3ef7eca13d46
Revises: 36bab5c949ef
Create Date: 2026-04-25 12:17:07.965947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef7eca13d46'
down_revision: Union[str, Sequence[str], None] = '36bab5c949ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('meeting_purpose', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('meeting_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('meeting_location', sa.String(length=200), nullable=True))
    op.add_column('documents', sa.Column('meeting_chairperson', sa.String(length=100), nullable=True))
    op.add_column('positions', sa.Column('weight', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_positions_weight'), 'positions', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_weight'), table_name='positions')
    op.drop_column('positions', 'weight')
    op.drop_column('documents', 'meeting_chairperson')
    op.drop_column('documents', 'meeting_location')
    op.drop_column('documents', 'meeting_time')
    op.drop_column('documents', 'meeting_purpose')
    # ### end Alembic commands ###
