"""add_shop_order_closes

Revision ID: 5865fc9c5f7e
Revises: 5694b02b3aeb
Create Date: 2026-07-04 15:49:00.198251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5865fc9c5f7e'
down_revision: Union[str, Sequence[str], None] = '5694b02b3aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('match_any_permissions', sa.JSON(), nullable=False),
    sa.Column('match_any_prefixes', sa.JSON(), nullable=False),
    sa.Column('exclude_permissions', sa.JSON(), nullable=False),
    sa.Column('exclude_prefixes', sa.JSON(), nullable=False),
    sa.Column('desktop_sections', sa.JSON(), nullable=False),
    sa.Column('mobile_order', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_profiles_key'), 'navigation_profiles', ['key'], unique=True)
    op.create_table('org_google_calendar_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_email', sa.String(length=254), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_by', sa.UUID(), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=256), server_default='primary', nullable=False),
    sa.Column('sync_token', sa.String(length=500), nullable=True),
    sa.Column('sync_token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pull_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_org_google_calendar_configs_org')
    )
    op.create_index(op.f('ix_org_google_calendar_configs_org_id'), 'org_google_calendar_configs', ['org_id'], unique=False)
    op.create_table('navigation_profile_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['navigation_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'position_id', name='uq_navigation_profile_position')
    )
    op.create_index(op.f('ix_navigation_profile_positions_position_id'), 'navigation_profile_positions', ['position_id'], unique=False)
    op.create_index(op.f('ix_navigation_profile_positions_profile_id'), 'navigation_profile_positions', ['profile_id'], unique=False)
    op.create_table('shop_order_closes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=False),
    sa.Column('reopened_by_id', sa.UUID(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reopened_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_closes_category_id'), 'shop_order_closes', ['category_id'], unique=False)
    op.create_index(op.f('ix_shop_order_closes_class_id'), 'shop_order_closes', ['class_id'], unique=False)
    op.create_index(op.f('ix_shop_order_closes_is_active'), 'shop_order_closes', ['is_active'], unique=False)
    op.drop_index(op.f('ix_audit_logs_actor_email_created_at'), table_name='audit_logs')
    op.add_column('calendar_events', sa.Column('google_event_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_calendar_events_google_event_id'), 'calendar_events', ['google_event_id'], unique=False)
    op.drop_index(op.f('ix_document_revisions_changed_by'), table_name='document_revisions')
    op.drop_index(op.f('ix_email_messages_created_at_status'), table_name='email_messages')
    op.drop_index(op.f('ix_inventory_procurement_items_item_id'), table_name='inventory_procurement_items')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_meeting_agenda_items_regulation_id'), table_name='meeting_agenda_items')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_index(op.f('ix_person_affiliations_person_kind_status'), table_name='person_affiliations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_person_affiliations_person_kind_status'), 'person_affiliations', ['person_id', 'kind', 'status'], unique=False)
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_regulation_id'), 'meeting_agenda_items', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_procurement_items_item_id'), 'inventory_procurement_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_email_messages_created_at_status'), 'email_messages', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_document_revisions_changed_by'), 'document_revisions', ['changed_by'], unique=False)
    op.drop_index(op.f('ix_calendar_events_google_event_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'google_event_id')
    op.create_index(op.f('ix_audit_logs_actor_email_created_at'), 'audit_logs', ['actor_email', 'created_at'], unique=False)
    op.drop_index(op.f('ix_shop_order_closes_is_active'), table_name='shop_order_closes')
    op.drop_index(op.f('ix_shop_order_closes_class_id'), table_name='shop_order_closes')
    op.drop_index(op.f('ix_shop_order_closes_category_id'), table_name='shop_order_closes')
    op.drop_table('shop_order_closes')
    op.drop_index(op.f('ix_navigation_profile_positions_profile_id'), table_name='navigation_profile_positions')
    op.drop_index(op.f('ix_navigation_profile_positions_position_id'), table_name='navigation_profile_positions')
    op.drop_table('navigation_profile_positions')
    op.drop_index(op.f('ix_org_google_calendar_configs_org_id'), table_name='org_google_calendar_configs')
    op.drop_table('org_google_calendar_configs')
    op.drop_index(op.f('ix_navigation_profiles_key'), table_name='navigation_profiles')
    op.drop_table('navigation_profiles')
    # ### end Alembic commands ###
