"""新增公文陳情關聯

Revision ID: 7a3fe68a9741
Revises: 1602a7684c1d
Create Date: 2026-09-10 11:33:30.504162

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a3fe68a9741"
down_revision: str | Sequence[str] | None = "1602a7684c1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("petition_case_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_documents_petition_case_id"), "documents", ["petition_case_id"])
    op.create_foreign_key(
        "fk_documents_petition_case_id",
        "documents",
        "petition_cases",
        ["petition_case_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "petition_case_events", sa.Column("related_document_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_petition_case_events_related_document_id"),
        "petition_case_events",
        ["related_document_id"],
    )
    op.create_foreign_key(
        "fk_petition_case_events_related_document_id",
        "petition_case_events",
        "documents",
        ["related_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_petition_case_events_related_document_id",
        "petition_case_events",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_petition_case_events_related_document_id"), table_name="petition_case_events"
    )
    op.drop_column("petition_case_events", "related_document_id")
    op.drop_constraint("fk_documents_petition_case_id", "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_petition_case_id"), table_name="documents")
    op.drop_column("documents", "petition_case_id")
    # ### end Alembic commands ###
