"""描述

Revision ID: 8e04df8dd031
Revises: c80fc3373db9
Create Date: 2026-04-09 22:11:44.588580

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8e04df8dd031'
down_revision: str | Sequence[str] | None = 'c80fc3373db9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
