"""converge index/constraint drift (council_proposals, judicial_petitions, public_link_categories)

Revision ID: 8ee2f4be16ce
Revises: 20260604agendaproposal
Create Date: 2026-06-04 16:29:52.639226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee2f4be16ce'
down_revision: Union[str, Sequence[str], None] = '20260604agendaproposal'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('council_proposals_serial_number_key'), 'council_proposals', type_='unique')
    op.drop_index(op.f('ix_council_proposals_serial_number'), table_name='council_proposals')
    op.create_index(op.f('ix_council_proposals_serial_number'), 'council_proposals', ['serial_number'], unique=True)
    op.drop_index(op.f('ix_judicial_petitions_petition_type'), table_name='judicial_petitions')
    op.drop_constraint(op.f('judicial_petitions_docket_number_key'), 'judicial_petitions', type_='unique')
    op.drop_index(op.f('ix_judicial_petitions_docket_number'), table_name='judicial_petitions')
    op.create_index(op.f('ix_judicial_petitions_docket_number'), 'judicial_petitions', ['docket_number'], unique=True)
    op.create_index(op.f('ix_public_link_categories_is_active'), 'public_link_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_public_link_categories_sort_order'), 'public_link_categories', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_link_categories_sort_order'), table_name='public_link_categories')
    op.drop_index(op.f('ix_public_link_categories_is_active'), table_name='public_link_categories')
    op.drop_index(op.f('ix_judicial_petitions_docket_number'), table_name='judicial_petitions')
    op.create_index(op.f('ix_judicial_petitions_docket_number'), 'judicial_petitions', ['docket_number'], unique=False)
    op.create_unique_constraint(op.f('judicial_petitions_docket_number_key'), 'judicial_petitions', ['docket_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_judicial_petitions_petition_type'), 'judicial_petitions', ['petition_type'], unique=False)
    op.drop_index(op.f('ix_council_proposals_serial_number'), table_name='council_proposals')
    op.create_index(op.f('ix_council_proposals_serial_number'), 'council_proposals', ['serial_number'], unique=False)
    op.create_unique_constraint(op.f('council_proposals_serial_number_key'), 'council_proposals', ['serial_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
