"""catch_up_drift_after_db_reset

Revision ID: 98ecdc290340
Revises: 20260601090000
Create Date: 2026-06-01 03:59:09.196360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ecdc290340'
down_revision: Union[str, Sequence[str], None] = '20260601090000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('s3_bucket', sa.String(length=200), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hex', sa.String(length=64), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_records_kind_created', 'backup_records', ['kind', 'created_at'], unique=False)
    op.create_index('ix_backup_records_status', 'backup_records', ['status'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_globally_enabled', sa.Boolean(), nullable=False),
    sa.Column('percentage_rollout', sa.Integer(), nullable=False),
    sa.Column('enabled_user_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled_permission_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_feature_flags_key')
    )
    op.create_index('ix_feature_flags_enabled', 'feature_flags', ['is_globally_enabled'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('encrypted_key', sa.String(length=500), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_key_hash')
    )
    op.create_index('ix_api_keys_owner', 'api_keys', ['owner_user_id'], unique=False)
    op.create_index('ix_api_keys_revoked', 'api_keys', ['revoked_at'], unique=False)
    op.create_table('audit_log_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('last_audit_log_id', sa.UUID(), nullable=True),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('log_count', sa.Integer(), nullable=False),
    sa.Column('s3_object_url', sa.String(length=500), nullable=True),
    sa.Column('s3_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integrity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anchor_date', name='uq_audit_log_anchors_date')
    )
    op.create_index('ix_audit_log_anchors_date', 'audit_log_anchors', ['anchor_date'], unique=False)
    op.create_table('discord_notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('digest_daily_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('digest_weekly_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Taipei', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_user_identities_provider_external_id')
    )
    op.create_index('ix_user_identities_provider_email', 'user_identities', ['provider', 'email'], unique=False)
    op.create_index('ix_user_identities_user', 'user_identities', ['user_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_subs_active', 'webhook_subscriptions', ['is_active'], unique=False)
    op.create_index('ix_webhook_subs_owner', 'webhook_subscriptions', ['owner_user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_scheduled', 'webhook_deliveries', ['scheduled_at'], unique=False)
    op.create_index('ix_webhook_deliveries_status', 'webhook_deliveries', ['status'], unique=False)
    op.create_index('ix_webhook_deliveries_sub', 'webhook_deliveries', ['subscription_id'], unique=False)
    # NOTE: announcements.search_vector / documents.search_vector 為 migration 20260527120000
    # 建立的 PostgreSQL GENERATED column，model 已對應宣告，故不在此 drop。
    op.add_column('audit_logs', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('self_hash', sa.String(length=64), nullable=True))
    op.create_index('ix_audit_logs_self_hash', 'audit_logs', ['self_hash'], unique=False)
    op.drop_constraint(op.f('discord_account_links_discord_user_id_key'), 'discord_account_links', type_='unique')
    op.drop_constraint(op.f('discord_account_links_user_id_key'), 'discord_account_links', type_='unique')
    op.drop_index(op.f('ix_discord_account_links_discord_user_id'), table_name='discord_account_links')
    op.create_index(op.f('ix_discord_account_links_discord_user_id'), 'discord_account_links', ['discord_user_id'], unique=True)
    op.drop_index(op.f('ix_discord_account_links_user_id'), table_name='discord_account_links')
    op.create_index(op.f('ix_discord_account_links_user_id'), 'discord_account_links', ['user_id'], unique=True)
    op.drop_constraint(op.f('discord_guild_configs_guild_id_key'), 'discord_guild_configs', type_='unique')
    op.drop_index(op.f('ix_discord_guild_configs_guild_id'), table_name='discord_guild_configs')
    op.create_index(op.f('ix_discord_guild_configs_guild_id'), 'discord_guild_configs', ['guild_id'], unique=True)
    op.add_column('document_approvals', sa.Column('parallel_group', sa.Integer(), nullable=True))
    op.add_column('document_approvals', sa.Column('approval_mode', sa.String(length=10), nullable=True))
    op.add_column('documents', sa.Column('reminder_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('line_account_links_line_user_id_key'), 'line_account_links', type_='unique')
    op.drop_constraint(op.f('line_account_links_user_id_key'), 'line_account_links', type_='unique')
    op.drop_index(op.f('ix_meeting_attendance_voting_class_id'), table_name='meeting_attendance')
    op.drop_index(op.f('uq_meeting_attendance_voting_class'), table_name='meeting_attendance', postgresql_where='((is_voting_eligible = true) AND (voting_class_id IS NOT NULL))')
    op.alter_column('partner_businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_person_affiliations_academic_year'), 'person_affiliations', ['academic_year'], unique=False)
    op.create_index(op.f('ix_person_affiliations_kind'), 'person_affiliations', ['kind'], unique=False)
    op.create_index(op.f('ix_person_affiliations_status'), 'person_affiliations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_affiliations_status'), table_name='person_affiliations')
    op.drop_index(op.f('ix_person_affiliations_kind'), table_name='person_affiliations')
    op.drop_index(op.f('ix_person_affiliations_academic_year'), table_name='person_affiliations')
    op.alter_column('partner_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uq_meeting_attendance_voting_class'), 'meeting_attendance', ['meeting_id', 'voting_class_id'], unique=True, postgresql_where='((is_voting_eligible = true) AND (voting_class_id IS NOT NULL))')
    op.create_index(op.f('ix_meeting_attendance_voting_class_id'), 'meeting_attendance', ['voting_class_id'], unique=False)
    op.create_unique_constraint(op.f('line_account_links_user_id_key'), 'line_account_links', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('line_account_links_line_user_id_key'), 'line_account_links', ['line_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'last_reminded_at')
    op.drop_column('documents', 'reminder_count')
    op.drop_column('document_approvals', 'approval_mode')
    op.drop_column('document_approvals', 'parallel_group')
    op.drop_index(op.f('ix_discord_guild_configs_guild_id'), table_name='discord_guild_configs')
    op.create_index(op.f('ix_discord_guild_configs_guild_id'), 'discord_guild_configs', ['guild_id'], unique=False)
    op.create_unique_constraint(op.f('discord_guild_configs_guild_id_key'), 'discord_guild_configs', ['guild_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_discord_account_links_user_id'), table_name='discord_account_links')
    op.create_index(op.f('ix_discord_account_links_user_id'), 'discord_account_links', ['user_id'], unique=False)
    op.drop_index(op.f('ix_discord_account_links_discord_user_id'), table_name='discord_account_links')
    op.create_index(op.f('ix_discord_account_links_discord_user_id'), 'discord_account_links', ['discord_user_id'], unique=False)
    op.create_unique_constraint(op.f('discord_account_links_user_id_key'), 'discord_account_links', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('discord_account_links_discord_user_id_key'), 'discord_account_links', ['discord_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_audit_logs_self_hash', table_name='audit_logs')
    op.drop_column('audit_logs', 'self_hash')
    op.drop_column('audit_logs', 'prev_hash')
    op.drop_index('ix_webhook_deliveries_sub', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_status', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_scheduled', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_webhook_subs_owner', table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subs_active', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index('ix_user_identities_user', table_name='user_identities')
    op.drop_index('ix_user_identities_provider_email', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('discord_notification_preferences')
    op.drop_index('ix_audit_log_anchors_date', table_name='audit_log_anchors')
    op.drop_table('audit_log_anchors')
    op.drop_index('ix_api_keys_revoked', table_name='api_keys')
    op.drop_index('ix_api_keys_owner', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_feature_flags_enabled', table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index('ix_backup_records_status', table_name='backup_records')
    op.drop_index('ix_backup_records_kind_created', table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
