"""add_article_type_values

Revision ID: 9ac59ea6117b
Revises: ab702da0cae9
Create Date: 2026-04-23 22:12:02.341368

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ac59ea6117b'
down_revision: str | Sequence[str] | None = 'ab702da0cae9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── 新增 ArticleType ENUM 值（PostgreSQL 不支援 autogenerate 偵測 ENUM 變更）──
    # article=條, paragraph=項, subparagraph=款, item=目
    conn = op.get_bind()
    for new_value in ("article", "paragraph", "subparagraph", "item"):
        conn.execute(sa.text(
            f"ALTER TYPE articletype ADD VALUE IF NOT EXISTS '{new_value}'"
        ))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_serial_templates_created_by'), 'document_serial_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_meal_order_items_menu_item_id'), 'meal_order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_meal_order_items_order_id'), 'meal_order_items', ['order_id'], unique=False)
    op.drop_constraint(op.f('meal_orders_serial_number_key'), 'meal_orders', type_='unique')
    op.drop_constraint(op.f('uq_meal_orders_pickup_code'), 'meal_orders', type_='unique')
    op.drop_index(op.f('ix_meal_orders_pickup_code'), table_name='meal_orders')
    op.create_index(op.f('ix_meal_orders_pickup_code'), 'meal_orders', ['pickup_code'], unique=True)
    op.create_index(op.f('ix_meal_orders_schedule_id'), 'meal_orders', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_meal_orders_serial_number'), 'meal_orders', ['serial_number'], unique=True)
    op.create_index(op.f('ix_meal_orders_user_id'), 'meal_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_orders_vendor_id'), 'meal_orders', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_meal_vendors_created_by'), 'meal_vendors', ['created_by'], unique=False)
    op.create_index(op.f('ix_meal_vendors_org_id'), 'meal_vendors', ['org_id'], unique=False)
    op.create_index(op.f('ix_menu_items_schedule_id'), 'menu_items', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_menu_schedules_created_by'), 'menu_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_menu_schedules_date'), 'menu_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_menu_schedules_is_closed'), 'menu_schedules', ['is_closed'], unique=False)
    op.create_index(op.f('ix_menu_schedules_vendor_id'), 'menu_schedules', ['vendor_id'], unique=False)
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index(op.f('ix_survey_answers_question_id'), 'survey_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_survey_answers_response_id'), 'survey_answers', ['response_id'], unique=False)
    op.create_index(op.f('ix_survey_questions_survey_id'), 'survey_questions', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_anon_token'), 'survey_responses', ['anon_token'], unique=False)
    op.create_index(op.f('ix_survey_responses_respondent_id'), 'survey_responses', ['respondent_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_surveys_created_by'), 'surveys', ['created_by'], unique=False)
    op.create_index(op.f('ix_surveys_org_id'), 'surveys', ['org_id'], unique=False)
    op.create_index(op.f('ix_surveys_title'), 'surveys', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_title'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_org_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_created_by'), table_name='surveys')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_respondent_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_anon_token'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_questions_survey_id'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_answers_response_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_survey_answers_question_id'), table_name='survey_answers')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.drop_index(op.f('ix_menu_schedules_vendor_id'), table_name='menu_schedules')
    op.drop_index(op.f('ix_menu_schedules_is_closed'), table_name='menu_schedules')
    op.drop_index(op.f('ix_menu_schedules_date'), table_name='menu_schedules')
    op.drop_index(op.f('ix_menu_schedules_created_by'), table_name='menu_schedules')
    op.drop_index(op.f('ix_menu_items_schedule_id'), table_name='menu_items')
    op.drop_index(op.f('ix_meal_vendors_org_id'), table_name='meal_vendors')
    op.drop_index(op.f('ix_meal_vendors_created_by'), table_name='meal_vendors')
    op.drop_index(op.f('ix_meal_orders_vendor_id'), table_name='meal_orders')
    op.drop_index(op.f('ix_meal_orders_user_id'), table_name='meal_orders')
    op.drop_index(op.f('ix_meal_orders_serial_number'), table_name='meal_orders')
    op.drop_index(op.f('ix_meal_orders_schedule_id'), table_name='meal_orders')
    op.drop_index(op.f('ix_meal_orders_pickup_code'), table_name='meal_orders')
    op.create_index(op.f('ix_meal_orders_pickup_code'), 'meal_orders', ['pickup_code'], unique=False)
    op.create_unique_constraint(op.f('uq_meal_orders_pickup_code'), 'meal_orders', ['pickup_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('meal_orders_serial_number_key'), 'meal_orders', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_meal_order_items_order_id'), table_name='meal_order_items')
    op.drop_index(op.f('ix_meal_order_items_menu_item_id'), table_name='meal_order_items')
    op.drop_index(op.f('ix_document_serial_templates_created_by'), table_name='document_serial_templates')
    # ### end Alembic commands ###
