"""新增校商投稿模組

Revision ID: a46fd15e77d1
Revises: 8d27baee5bbf
Create Date: 2026-07-20 01:49:52.447385

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a46fd15e77d1"
down_revision: str | Sequence[str] | None = "8d27baee5bbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchandise_submission_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("specification", sa.Text(), nullable=True),
        sa.Column(
            "template_images",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "custom_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_open_override", sa.Boolean(), nullable=True),
        sa.Column("opens_at_override", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at_override", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_file_size_mb_override", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchandise_submission_items_created_by_id"),
        "merchandise_submission_items",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merchandise_submission_items_name"),
        "merchandise_submission_items",
        ["name"],
        unique=False,
    )
    op.create_table(
        "merchandise_submission_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_open", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_file_size_mb", sa.Integer(), server_default="100", nullable=False),
        sa.Column("announcement", sa.Text(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchandise_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "REVIEWING",
                "APPROVED",
                "REVISION_REQUESTED",
                "REJECTED",
                name="merchandisesubmissionstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "account_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "field_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["merchandise_submission_items.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchandise_submissions_item_id"),
        "merchandise_submissions",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merchandise_submissions_status"),
        "merchandise_submissions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merchandise_submissions_user_id"),
        "merchandise_submissions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "merchandise_submission_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["merchandise_submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_merchandise_submission_files_submission_id"),
        "merchandise_submission_files",
        ["submission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_merchandise_submission_files_submission_id"),
        table_name="merchandise_submission_files",
    )
    op.drop_table("merchandise_submission_files")
    op.drop_index(op.f("ix_merchandise_submissions_user_id"), table_name="merchandise_submissions")
    op.drop_index(op.f("ix_merchandise_submissions_status"), table_name="merchandise_submissions")
    op.drop_index(op.f("ix_merchandise_submissions_item_id"), table_name="merchandise_submissions")
    op.drop_table("merchandise_submissions")
    op.drop_table("merchandise_submission_settings")
    op.drop_index(
        op.f("ix_merchandise_submission_items_name"), table_name="merchandise_submission_items"
    )
    op.drop_index(
        op.f("ix_merchandise_submission_items_created_by_id"),
        table_name="merchandise_submission_items",
    )
    op.drop_table("merchandise_submission_items")
    # ### end Alembic commands ###
