"""add_user_phone_fields

Revision ID: a64cf15a8918
Revises: 9ac59ea6117b
Create Date: 2026-04-24 12:46:53.199270

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a64cf15a8918'
down_revision: str | Sequence[str] | None = '9ac59ea6117b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('show_phone', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('show_email', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_email')
    op.drop_column('users', 'show_phone')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
