"""add missing workflow_instances indexes

Revision ID: abe48bddbc4e
Revises: 20260604crossmodule
Create Date: 2026-06-04 16:54:50.110334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe48bddbc4e'
down_revision: Union[str, Sequence[str], None] = '20260604crossmodule'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflow_instances_activity_id'), 'workflow_instances', ['activity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_org_id'), 'workflow_instances', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_type'), 'workflow_instances', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instances_workflow_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_org_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_activity_id'), table_name='workflow_instances')
    # ### end Alembic commands ###
