"""add_missing_fk_indexes_shop

Revision ID: ceb7192a7f99
Revises: f87b2273c9e3
Create Date: 2026-07-06 14:11:56.481181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb7192a7f99'
down_revision: Union[str, Sequence[str], None] = 'f87b2273c9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_categories_created_by'), 'product_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_shop_order_closes_closed_by_id'), 'shop_order_closes', ['closed_by_id'], unique=False)
    op.create_index(op.f('ix_shop_order_closes_reopened_by_id'), 'shop_order_closes', ['reopened_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_order_closes_reopened_by_id'), table_name='shop_order_closes')
    op.drop_index(op.f('ix_shop_order_closes_closed_by_id'), table_name='shop_order_closes')
    op.drop_index(op.f('ix_product_categories_created_by'), table_name='product_categories')
    # ### end Alembic commands ###
