"""add_regulation_shop_tables

Revision ID: d05c8d53bf3a
Revises: d92df2e7d052
Create Date: 2026-04-09 23:49:29.982365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05c8d53bf3a'
down_revision: Union[str, Sequence[str], None] = 'd92df2e7d052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    def upgrade() -> None:
        # 建立序號
        op.execute("CREATE SEQUENCE IF NOT EXISTS order_serial_seq START 1")
        op.execute("CREATE SEQUENCE IF NOT EXISTS document_serial_seq START 1")
        # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
