"""add_notification_preferences_to_user

Revision ID: de3a735c3e6b
Revises: c8d9e0f1a2b3
Create Date: 2026-05-08 00:10:41.417652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de3a735c3e6b'
down_revision: Union[str, Sequence[str], None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_reads')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_user_id'), 'announcement_reads', ['user_id'], unique=False)
    op.drop_index(op.f('ix_judicial_documents_case_id'), table_name='judicial_documents')
    op.drop_index(op.f('ix_judicial_documents_created_by'), table_name='judicial_documents')
    op.drop_index(op.f('ix_judicial_documents_doc_type'), table_name='judicial_documents')
    op.drop_index(op.f('ix_judicial_documents_is_public'), table_name='judicial_documents')
    op.drop_table('judicial_documents')
    op.drop_index(op.f('ix_judicial_cases_case_no'), table_name='judicial_cases')
    op.drop_index(op.f('ix_judicial_cases_created_by'), table_name='judicial_cases')
    op.drop_index(op.f('ix_judicial_cases_status'), table_name='judicial_cases')
    op.drop_table('judicial_cases')
    op.add_column('regulations', sa.Column('is_repealed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('regulations', sa.Column('repealed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('regulations', sa.Column('repeal_reason', sa.Text(), nullable=True))
    op.add_column('regulations', sa.Column('repeal_replacement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_regulations_repeal_replacement_id'), 'regulations', ['repeal_replacement_id'], unique=False)
    op.create_foreign_key(None, 'regulations', 'regulations', ['repeal_replacement_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('notification_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_constraint(None, 'regulations', type_='foreignkey')
    op.drop_index(op.f('ix_regulations_repeal_replacement_id'), table_name='regulations')
    op.drop_column('regulations', 'repeal_replacement_id')
    op.drop_column('regulations', 'repeal_reason')
    op.drop_column('regulations', 'repealed_date')
    op.drop_column('regulations', 'is_repealed')
    op.create_table('judicial_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_type', postgresql.ENUM('decision', 'interpretation', 'indictment', 'judgment', 'order', 'other', name='judicialdocumenttype'), server_default=sa.text("'decision'::judicialdocumenttype"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('regulation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['judicial_cases.id'], name=op.f('fk_judicial_documents_case_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('judicial_documents_pkey'))
    )
    op.create_index(op.f('ix_judicial_documents_is_public'), 'judicial_documents', ['is_public'], unique=False)
    op.create_index(op.f('ix_judicial_documents_doc_type'), 'judicial_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_judicial_documents_created_by'), 'judicial_documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_judicial_documents_case_id'), 'judicial_documents', ['case_id'], unique=False)
    op.create_table('judicial_cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_no', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'closed', name='judicialcasestatus'), server_default=sa.text("'open'::judicialcasestatus"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_judicial_cases_created_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('judicial_cases_pkey')),
    sa.UniqueConstraint('case_no', name=op.f('uq_judicial_case_no'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_judicial_cases_status'), 'judicial_cases', ['status'], unique=False)
    op.create_index(op.f('ix_judicial_cases_created_by'), 'judicial_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_judicial_cases_case_no'), 'judicial_cases', ['case_no'], unique=False)
    op.drop_index(op.f('ix_announcement_reads_user_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    # ### end Alembic commands ###
