"""sync menu_schedules class fields and index drift

Revision ID: defc1e68a276
Revises: 20260521_meeting_v2
Create Date: 2026-05-21 22:48:25.690245

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "defc1e68a276"
down_revision: str | Sequence[str] | None = "20260521_meeting_v2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_carts_user"), "carts", type_="unique")
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=True)
    op.alter_column(
        "class_memberships",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "class_memberships",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_class_memberships_academic_year"),
        "class_memberships",
        ["academic_year"],
        unique=False,
    )
    op.alter_column(
        "class_role_bindings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "class_role_bindings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_class_pickup_codes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_class_pickup_codes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("meal_class_pickup_codes_code_key"), "meal_class_pickup_codes", type_="unique"
    )
    op.drop_index(op.f("ix_meal_class_pickup_codes_code"), table_name="meal_class_pickup_codes")
    op.create_index(
        op.f("ix_meal_class_pickup_codes_code"), "meal_class_pickup_codes", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_meal_class_pickup_codes_class_id"),
        "meal_class_pickup_codes",
        ["class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_class_pickup_codes_issued_to_id"),
        "meal_class_pickup_codes",
        ["issued_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_class_pickup_codes_pickup_slot_id"),
        "meal_class_pickup_codes",
        ["pickup_slot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_class_pickup_codes_vendor_id"),
        "meal_class_pickup_codes",
        ["vendor_id"],
        unique=False,
    )
    op.alter_column(
        "meal_pickup_slots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_pickup_slots",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_product_availabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_product_availabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_meal_product_availabilities_is_available"),
        "meal_product_availabilities",
        ["is_available"],
        unique=False,
    )
    op.alter_column(
        "meal_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_applications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_applications",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_managers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_managers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_meeting_artifact_links_agenda_item_id"),
        "meeting_artifact_links",
        ["agenda_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_attendance_sources_meeting_id"),
        "meeting_attendance_sources",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_decisions_agenda_item_id"),
        "meeting_decisions",
        ["agenda_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_decisions_meeting_id"), "meeting_decisions", ["meeting_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_motions_meeting_id"), "meeting_motions", ["meeting_id"], unique=False
    )
    op.drop_constraint(op.f("meetings_checkin_token_key"), "meetings", type_="unique")
    op.drop_constraint(op.f("meetings_screen_token_key"), "meetings", type_="unique")
    op.drop_index(op.f("ix_meetings_checkin_token"), table_name="meetings")
    op.create_index(op.f("ix_meetings_checkin_token"), "meetings", ["checkin_token"], unique=True)
    op.drop_index(op.f("ix_meetings_screen_token"), table_name="meetings")
    op.create_index(op.f("ix_meetings_screen_token"), "meetings", ["screen_token"], unique=True)
    op.add_column("menu_schedules", sa.Column("availability_id", sa.UUID(), nullable=True))
    op.add_column("menu_schedules", sa.Column("pickup_slot_id", sa.UUID(), nullable=True))
    op.add_column("menu_schedules", sa.Column("class_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_menu_schedules_availability_id"),
        "menu_schedules",
        ["availability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menu_schedules_class_id"), "menu_schedules", ["class_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_schedules_pickup_slot_id"), "menu_schedules", ["pickup_slot_id"], unique=False
    )
    op.create_foreign_key(
        "fk_menu_schedules_availability_id",
        "menu_schedules",
        "meal_product_availabilities",
        ["availability_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_menu_schedules_class_id",
        "menu_schedules",
        "school_classes",
        ["class_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_menu_schedules_pickup_slot_id",
        "menu_schedules",
        "meal_pickup_slots",
        ["pickup_slot_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_menu_schedules_pickup_slot_id", "menu_schedules", type_="foreignkey")
    op.drop_constraint("fk_menu_schedules_class_id", "menu_schedules", type_="foreignkey")
    op.drop_constraint("fk_menu_schedules_availability_id", "menu_schedules", type_="foreignkey")
    op.drop_index(op.f("ix_menu_schedules_pickup_slot_id"), table_name="menu_schedules")
    op.drop_index(op.f("ix_menu_schedules_class_id"), table_name="menu_schedules")
    op.drop_index(op.f("ix_menu_schedules_availability_id"), table_name="menu_schedules")
    op.drop_column("menu_schedules", "class_id")
    op.drop_column("menu_schedules", "pickup_slot_id")
    op.drop_column("menu_schedules", "availability_id")
    op.drop_index(op.f("ix_meetings_screen_token"), table_name="meetings")
    op.create_index(op.f("ix_meetings_screen_token"), "meetings", ["screen_token"], unique=False)
    op.drop_index(op.f("ix_meetings_checkin_token"), table_name="meetings")
    op.create_index(op.f("ix_meetings_checkin_token"), "meetings", ["checkin_token"], unique=False)
    op.create_unique_constraint(
        op.f("meetings_screen_token_key"),
        "meetings",
        ["screen_token"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("meetings_checkin_token_key"),
        "meetings",
        ["checkin_token"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_meeting_motions_meeting_id"), table_name="meeting_motions")
    op.drop_index(op.f("ix_meeting_decisions_meeting_id"), table_name="meeting_decisions")
    op.drop_index(op.f("ix_meeting_decisions_agenda_item_id"), table_name="meeting_decisions")
    op.drop_index(
        op.f("ix_meeting_attendance_sources_meeting_id"), table_name="meeting_attendance_sources"
    )
    op.drop_index(
        op.f("ix_meeting_artifact_links_agenda_item_id"), table_name="meeting_artifact_links"
    )
    op.alter_column(
        "meal_vendor_managers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_managers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_applications",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_vendor_applications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_meal_product_availabilities_is_available"),
        table_name="meal_product_availabilities",
    )
    op.alter_column(
        "meal_product_availabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_product_availabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_pickup_slots",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_pickup_slots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_meal_class_pickup_codes_vendor_id"), table_name="meal_class_pickup_codes"
    )
    op.drop_index(
        op.f("ix_meal_class_pickup_codes_pickup_slot_id"), table_name="meal_class_pickup_codes"
    )
    op.drop_index(
        op.f("ix_meal_class_pickup_codes_issued_to_id"), table_name="meal_class_pickup_codes"
    )
    op.drop_index(op.f("ix_meal_class_pickup_codes_class_id"), table_name="meal_class_pickup_codes")
    op.drop_index(op.f("ix_meal_class_pickup_codes_code"), table_name="meal_class_pickup_codes")
    op.create_index(
        op.f("ix_meal_class_pickup_codes_code"), "meal_class_pickup_codes", ["code"], unique=False
    )
    op.create_unique_constraint(
        op.f("meal_class_pickup_codes_code_key"),
        "meal_class_pickup_codes",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "meal_class_pickup_codes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "meal_class_pickup_codes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "class_role_bindings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "class_role_bindings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_class_memberships_academic_year"), table_name="class_memberships")
    op.alter_column(
        "class_memberships",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "class_memberships",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.create_unique_constraint(
        op.f("uq_carts_user"), "carts", ["user_id"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
