"""sync database schema with models

Revision ID: fbc1a34fda7d
Revises: 2f3e4d5c6b7a
Create Date: 2026-05-14 01:20:07.104317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc1a34fda7d'
down_revision: Union[str, Sequence[str], None] = '2f3e4d5c6b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_created_by_status', 'documents', ['created_by', 'status'], unique=False)
    op.create_index('ix_documents_org_status', 'documents', ['org_id', 'status'], unique=False)
    op.create_index('ix_documents_status_created_at', 'documents', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_status_created_at', table_name='documents')
    op.drop_index('ix_documents_org_status', table_name='documents')
    op.drop_index('ix_documents_created_by_status', table_name='documents')
    # ### end Alembic commands ###
