"""add finance ledger

Revision ID: fcc2e2a0b001
Revises: fbc1a34fda7d
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "fcc2e2a0b001"
down_revision: str | Sequence[str] | None = "fbc1a34fda7d"
branch_labels = None
depends_on = None

def upgrade() -> None:
    uid = postgresql.UUID(as_uuid=True)
    op.create_table("finance_ledgers", sa.Column("id", uid, primary_key=True), sa.Column("org_id", uid, sa.ForeignKey("orgs.id"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("currency", sa.String(3), nullable=False, server_default="TWD"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("org_id", name="uq_finance_ledger_org"))
    op.create_table("finance_fiscal_periods", sa.Column("id", uid, primary_key=True), sa.Column("ledger_id", uid, sa.ForeignKey("finance_ledgers.id"), nullable=False), sa.Column("name", sa.String(100), nullable=False), sa.Column("starts_on", sa.Date(), nullable=False), sa.Column("ends_on", sa.Date(), nullable=False), sa.Column("is_closed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("ledger_id", "name", name="uq_finance_period_name"))
    op.create_table("finance_chart_accounts", sa.Column("id", uid, primary_key=True), sa.Column("ledger_id", uid, sa.ForeignKey("finance_ledgers.id"), nullable=False), sa.Column("code", sa.String(20), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("account_type", sa.String(20), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("ledger_id", "code", name="uq_finance_account_code"))
    op.create_table("finance_fund_accounts", sa.Column("id", uid, primary_key=True), sa.Column("ledger_id", uid, sa.ForeignKey("finance_ledgers.id"), nullable=False), sa.Column("chart_account_id", uid, sa.ForeignKey("finance_chart_accounts.id"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("storage_type", sa.String(20), nullable=False), sa.Column("bank_name", sa.String(120)), sa.Column("account_last_four", sa.String(4)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("ledger_id", "name", name="uq_finance_fund_name"))
    op.create_table("finance_journal_entries", sa.Column("id", uid, primary_key=True), sa.Column("ledger_id", uid, sa.ForeignKey("finance_ledgers.id"), nullable=False), sa.Column("period_id", uid, sa.ForeignKey("finance_fiscal_periods.id"), nullable=False), sa.Column("entry_date", sa.Date(), nullable=False), sa.Column("description", sa.String(300), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("created_by_id", uid, sa.ForeignKey("users.id"), nullable=False), sa.Column("reviewed_by_id", uid, sa.ForeignKey("users.id")), sa.Column("posted_at", sa.DateTime(timezone=True)), sa.Column("source_type", sa.String(50)), sa.Column("source_id", uid), sa.Column("source_event", sa.String(60)), sa.Column("source_url", sa.String(500)), sa.Column("evidence_url", sa.String(500)), sa.Column("note", sa.Text()), sa.Column("reversal_of_id", uid, sa.ForeignKey("finance_journal_entries.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("ledger_id", "source_type", "source_id", "source_event", name="uq_finance_source_event"))
    op.create_index("ix_finance_journal_ledger_status", "finance_journal_entries", ["ledger_id", "status"])
    op.create_table("finance_journal_lines", sa.Column("id", uid, primary_key=True), sa.Column("entry_id", uid, sa.ForeignKey("finance_journal_entries.id", ondelete="CASCADE"), nullable=False), sa.Column("account_id", uid, sa.ForeignKey("finance_chart_accounts.id"), nullable=False), sa.Column("debit", sa.Integer(), nullable=False, server_default="0"), sa.Column("credit", sa.Integer(), nullable=False, server_default="0"), sa.Column("memo", sa.String(240)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_finance_line_account", "finance_journal_lines", ["account_id"])
    op.create_table("finance_bank_transactions", sa.Column("id", uid, primary_key=True), sa.Column("fund_account_id", uid, sa.ForeignKey("finance_fund_accounts.id"), nullable=False), sa.Column("external_id", sa.String(180), nullable=False), sa.Column("occurred_on", sa.Date(), nullable=False), sa.Column("amount", sa.Integer(), nullable=False), sa.Column("description", sa.String(300), nullable=False), sa.Column("journal_entry_id", uid, sa.ForeignKey("finance_journal_entries.id")), sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("fund_account_id", "external_id", name="uq_finance_bank_external"))

def downgrade() -> None:
    op.drop_table("finance_bank_transactions"); op.drop_index("ix_finance_line_account", table_name="finance_journal_lines"); op.drop_table("finance_journal_lines"); op.drop_index("ix_finance_journal_ledger_status", table_name="finance_journal_entries"); op.drop_table("finance_journal_entries"); op.drop_table("finance_fund_accounts"); op.drop_table("finance_chart_accounts"); op.drop_table("finance_fiscal_periods"); op.drop_table("finance_ledgers")
